parameters: 
    eone.sonatacustomization.twig.global.class: Eone\SonataCustomizationBundle\Twig\GlobalVariables

services:
    eone.sonatacustomization.twig.global:
        class:  %eone.sonatacustomization.twig.global.class%
        arguments: 
            - "@service_container"